### ISSUE TITLE
Fix Level transition

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/Your-First-Game-Godot-2d-Platformer#21]
Currently the way we change between one level to another is by freeing the current and loading the next level manually, as mentioned in #1 we could simply just call `get_tree().change_scene` instead, like `Portal2Ds` were designed to do.

Regarding the interface we just need to add it to have it on both scenes, currently PlayScreen has the Levels, but we can invert this relationship somehow.

That was what I was talking about Friday, @razcore-art

**Comment by henriiquecampos** [comment]
In e816218a13c60b8b92e05a700820d16f1fc0409b, for instance, the second level should transition to the EndScreen, but since EndScreen isn't a level it doesn't have a `Portal2D` to connect to the `PlayScreen`, previously `Game`, so the game freezes.

**Comment by razcore-rad** [comment]
Alright, we can use `get_tree().change_scene`. Previously the problem was that the button interface was part of the `Game` scene and not the `Level` scene, but since we can make it part of the level scene and have that inheritance in place we can just use `get_tree().change_scene`, I'll work on this since I already made some tests.
