### ISSUE TITLE
Add Basic Enemies

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/Your-First-Game-Godot-2d-Platformer#3]
Enemies will have a basic physics implementation, moving left or right and changing their movement direction when they hit a wall, no AI whatsoever.

- [x] Gravity
- [x] Walking
- [x] Bouncing when hitting a wall
- [x] Kill Player

@NathanLovato can we add support for `VisibilityEnabler` on them, so they only start moving when they are inside the screen?

**Comment by henriiquecampos** [comment]
Should we add support for enemies to increase the player's score as well @NathanLovato ?

Scoring will already be implemented in #6 so I think it will be nice to have it on enemies as well.

**Comment by razcore-rad** [comment]
Yes using `VisibilityEnabler2D` is fine, I think including small bits that improve the overall project is just ok as long as it doesn't take too long to explain in a tutorial. `VisibilityEnabler2D` is ok for our purpose.

On the player score, I have a tiny proposal: make the enemies randomly drop coins that can be picked up by the player. I think Mario does this too right? I'm thinking the score is entirely coin-based so it makes sense that the enemies drop them instead of just adding to the score on death.
