### ISSUE TITLE
Sometimes Enemy doesn't die after player bounce

### ISSUE THREAD

**Issue by pixelprogrammer** [GDquest/Your-First-Game-Godot-2d-Platformer#34]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
At times, when you jump on the enemy, the enemy doesn't die but you still bounce off of them.

**What is the expected behavior?**
When you bounce off an enemy, it should die all the time.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1) Jump towards enemy
2) Try to clip the top left part of the enemies area2d box with the bottom right corner of the player

Another way you can trigger this is if the enemy is falling (not sure if falling enemy does anything extra)

**Comment by pixelprogrammer** [comment]
It looks like it has to do with the area2d's being wider than the body of the collisionShape2d. Because Enemy detects the body to enter its area it might collide with the area and not the body, thus, allowing the player to bounce without the enemy dying.

**Comment by henriiquecampos** [comment]
This is not **fixable**, but rather tweakable, with the current approach.

One way to guarantee a sync between the enemy dying and the player bouncing is by creating a stomp object, based on the player's kinematic body's kinematic collision and pass this object to the enemy and the player when their areas intersect, regardless how they intersect, it could even be circle areas covering them, and let them handle their logic based on this.

This is because with the kinematic collision we can access data relevant for the stomp, like the normal of the collision and based on that perform the stomp with data synced. This won't be possible with just Areas, they only handle overlapping and overlapping is not enough for a nice stomp mechanic.

Nonetheless, this edge case is fixed at https://github.com/GDQuest/godot-beginner-2d-platformer/commit/48b933e044d06251442e1ac4377f256b2ef63380

**Comment by NathanLovato** [comment]
We had issues back when it used kinematic collisions as well. I don't remember what that was exactly, but it had to do with keeping the code simple for the tutorial.

> Nonetheless, this edge case is fixed at 48b933e044d06251442e1ac4377f256b2ef63380

Did you forget to push a commit?

**Comment by henriiquecampos** [comment]
> I don't remember what that was exactly

Was because the logic was centralized in the Player and @razcore-art suggested to delegate the logic of killing the enemy to the enemy itself. Since the enemy couldn't detect a collision using its own KinematicBody (because its movement is just horizontal) we decided to go with Area2D. 

> Did you forget to push a commit?

I'm missing write access I guess.

edit: nevermind, git just forgot I was logged in

**Comment by pixelprogrammer** [comment]
Question, as game development and tutorials can be rather tricky, one of the ways I delegated this task was having the player call methods of the enemy to issue a hit or stomp.

Since the area2d or body collide with the stomp area, you do get the enemies area2d or collision body passed through the signal for access. I have interfaces (I'm using C#), so I typecast the object to an interface like `IStompable` if `null` do nothing, if not then call a method that tells the enemy they have been stomped like `gotStomped`, or something, and have that enemy do the rest like remove a hit point, or die if no hitpoints are left.

I am still relatively new to game development so I am not sure the best route to determine which objects manage the state, or call the state onto other objects in the gaming world, but this approach seems to work for me so far.

on a side note, the tutorials are some of the best so far for the Godot game engine. Much appreciated of the work you guys are doing 😎

**Comment by NathanLovato** [comment]
I'm not sure there, as we don't use c#. In GDScript you use a callback, or duck typing: with has_method for instance

**Comment by henriiquecampos** [comment]
That's pretty much what we did before @pixelprogrammer , but as a general rule is better if each object handles their own logic, whenever possible, that's why we delegated the two outcomes of a stomp to their respective objects.

We've talked a lot of these kinds of situations in games: single event, multiple effects on different objects.

In general, you create an object that will carry the data to the users. For instance, that's what we do for Hit/Hurtboxes in [gdquest/godot-platformer-2d](https://github.com/GDQuest/godot-platformer-2d/blob/master/game/src/Combat/HitBox/HitBox.gd), when they intersect we create a Hit object that both can access, pass data to and get data from. This way you create an object with the solo purpose of mediating these other two. You can check out the Mediator pattern to understand this concept better: https://refactoring.guru/design-patterns/mediator

**Comment by henriiquecampos** [comment]
This edge case is fixed in 48b933e044d06251442e1ac4377f256b2ef63380

So I think we can close this

**Comment by NathanLovato** [comment]
@henriiquecampos Thanks. Could you use `Close #...` or `Fix #...` in your commits directly, at the end, to close the issues?

**Comment by NathanLovato** [comment]
(in the future)
